language: node_js
dist: trusty
sudo: required
node_js: 8
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - CF_APP=watson-assistant-simple
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8
- provider: script
  skip_cleanup: true
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/assistant-simple
