language: node_js
dist: trusty
sudo: required
node_js: 8
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-assistant-simple
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
  - DATABASE_NAME=MSTravis
  - DATABASE_URI=mongodb+srv://user:user_password1@managersimulator-hnsxz.mongodb.net/MSTravis?retryWrites=true
