language: node_js
dist: trusty
sudo: required
node_js: 
- "node"
script:
- npm run test

cache:
  directories:
  - node_modules
env:
  global:
  - BX_APP=watson-assistant-simple
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos

